# NumPy tutorial

[Numerical Python](https://numpy.org) is one of the most fundamental tools in each data miner's toolbox. It is impossible to do serious data pre-processing and transformation without the understanding of `NumPy` and its most commonly used methods. The goal of this tutorial is to familiarize students with this awesome library.

## Introduction

Python is among the least efficient languages out there. Data mining is a field of study, which requires a lot of processing power. Why would we ever want to use python in order to do the data mining? The answer is really simple - we do not. We use python only as an interface to packages, which contain very efficient and optimized programs, such as numpy, scipy, sklearn, tensorflow, pytorch, keras... The list is long. Python is very flexible and simple. We just like its syntax, ability to combine it with programs written in other languages, not necessairly its efficency. In the previous tutorial we have already seen some numpy stuctures. When we imported the toy data sets, the data was stored in something called ndarray. In fact 99% of `NumPy` is about this very data structure and operations on this structure. `NumPy` stores everything in multidimensional arrays and vectorizes all operations on these arrays. 

Contrary to Python lists, the NumPy arrays represent tensors (e.g. 1st rank tensor - a vector, 2nd rank tensor - a matrix; do not confuse this with Tensorflow tensor data structure, tensors in a mathematical sense). Python list is just a list of things, specifically it could be a list of lists, there is no additional limitation to that. A tensor has some limitations:
- every element must be of the same type and size
- if an array has arrays, they must match as well

After all this:

\begin{matrix} 1 & 2 & 3 \\ 4 & 5 & 6 & 8 \\ 7 & 8 &  \end{matrix}

is not a matrix.

While this:



In [1]:
lst = [[1,2,3],[4,5,6,8],[7,8]]

is a list.

For a motivating example, let's compare the speed of computing an average of 10 mln of random numbers stored in a list vs an array

First, we are going to generate a list of 10 mln random numbers. We will use a function from the numpy package named randint. As you might suspect the function can be used to generate a random integer. In fact this function is flexible enough to create a tensor of any shape with random integers.

In [2]:
import numpy as np
from numpy.random import randint

randoms = randint(low=0, high=1000, size=(1000,1000))
randoms = randint(low=0, high=1000, size=(100,100,100))
randoms = randint(low=0, high=1000, size=(10,10000))
randoms = randint(low=0, high=1000, size=(10000000))
lst = list(randoms)

I hope you're not surprised the size is not just a single number. n-th rank tensor requires n numbers to describe its shape. A vector has just its length. A matrix has a number of columns and a number of rows. A cuboid has three dimensions, and so on. So, in the second to last line we generated a vector of 10 mln random numbers. In the last line we converted it to a list. We can get the length of this list with a built-in len function.

In [3]:
len(lst)

10000000

We expect the len function to return an integer. So it does. If we try to check the length of a numpy array we are going to get only the size of the first dimension. If we want to get a full description of the tensor shape, we can use the `shape` attribute.

In [4]:
sample = np.zeros((1000,1000,1000))

print(len(sample))
print(sample.shape)

1000
(1000, 1000, 1000)


Let's start the calculation of an average - we will use the cell magic here to compare the solutions.

In [5]:
%%time

# old-school iteration
summ = 0
for i in range(len(lst)):
    summ += lst[i]
    
print(f'Average = {summ/len(lst)}')

Average = 499.4265235
CPU times: user 1.33 s, sys: 4.08 ms, total: 1.34 s
Wall time: 1.34 s


In [6]:
%%time

# using built-ins sum() and len()
print(f'Average = {sum(lst)/len(lst)}')

Average = 499.4265235
CPU times: user 431 ms, sys: 2.14 ms, total: 433 ms
Wall time: 432 ms


In [7]:
%%time

# using NumPy
print(f'Average = {np.mean(randoms)}')

Average = 499.4265235
CPU times: user 5.73 ms, sys: 1.25 ms, total: 6.98 ms
Wall time: 5.1 ms


Let's see how to create an array and what happens when we start messing with the types and sizes of objects.

In the previous examples we already saw how to create an array of random numbers (and an array, which consists of zeros).
We can also create a numpy array with a python list, like this:

In [8]:
a = np.array([1, 2, 3, 4, 5])



we have also seen how to get the exact shape of an array. In fact there are more descriptors for an array.

In [9]:
print(f"""
Shape (sizes of dimensions): {a.shape}
Number of dimensions: {a.ndim}
Length (number of elements): {len(a)}
Size (number of nested elements): {a.size}
Type : {type(a)}
Data type (type of array elements): {a.dtype}
""")


Shape (sizes of dimensions): (5,)
Number of dimensions: 1
Length (number of elements): 5
Size (number of nested elements): 5
Type : <class 'numpy.ndarray'>
Data type (type of array elements): int64



Now let's see how the same descriptors can be applied to a two- and three -dimensional array

In [10]:
a = np.array([
    [1, 2, 3, 4, 5],
    [1, 4, 9, 16, 25]
])

print(f"""
Shape (sizes of dimensions): {a.shape}
Number of dimensions: {a.ndim}
Length (number of elements): {len(a)}
Size (number of nested elements): {a.size}
Type : {type(a)}
Data type (type of array elements): {a.dtype}
""")


Shape (sizes of dimensions): (2, 5)
Number of dimensions: 2
Length (number of elements): 2
Size (number of nested elements): 10
Type : <class 'numpy.ndarray'>
Data type (type of array elements): int64



In [11]:
a = np.array([
    [
    [1, 2, 3, 4, 5],
    [1, 1, 2, 3, 5]
    ],
    [
    [1, 2, 3, 4, 5],
    [1, 4, 9, 16, 25]
    ]
])

print(f"""
Shape (sizes of dimensions): {a.shape}
Number of dimensions: {a.ndim}
Length (number of elements): {len(a)}
Size (number of nested elements): {a.size}
Type : {type(a)}
Data type (type of array elements): {a.dtype}
""")


Shape (sizes of dimensions): (2, 2, 5)
Number of dimensions: 3
Length (number of elements): 2
Size (number of nested elements): 20
Type : <class 'numpy.ndarray'>
Data type (type of array elements): int64



Array elements should be of the same type. Let's see what happens if we mix two or more types.

In [12]:
a = np.array([1, 2, 'mary', 'had', 2.5, 'lambs'])
a

array(['1', '2', 'mary', 'had', '2.5', 'lambs'], dtype='<U32')

In [13]:
a.dtype

dtype('<U32')

We can also try to modify the length of array's elements

In [14]:
a = np.array(['mary', 'had', 'a', 'little', 'lamb'])
a.dtype

dtype('<U6')

In [15]:
a[4] = 'and very very very very long snake'
a

array(['mary', 'had', 'a', 'little', 'and ve'], dtype='<U6')

After an array has been created, it can be reshaped to whatever shape one desires. A special function is provided for transposing an array (changing rows into columns and vice versa)

In [16]:
a = np.array(list(range(12)))

a.shape = (3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [17]:
a = a.reshape(6, 2)
a

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [18]:
a.T

array([[ 0,  2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9, 11]])

## Creating arrays

The easiest way to create a 1-d array is to use a list. If you want a 2-d array, you use a list of lists. 3-d arrays are created using a list of lists of lists. You get the gist.

In [19]:
a_1d = np.array([1, 2, 3, 4])

a_2d = np.array([
    [1, 2, 3, 4],
    [1, 4, 9, 16],
    [1, 8, 27, 64]
])

a_3d = np.array([
    [
        [0, 0],
        [0, 1],
    ],
    [
        [1, 0],
        [1, 1],
    ],
])

There are utility functions in the `np` module for creating popular types of arrays:
- an array filled with zeros
- an array filled with ones
- an array filled with any value
- an array of consecutive (or stepped) values
- an array filled with random values
- a diagonal array

In [20]:
np.zeros(shape=(3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [21]:
np.zeros(shape=(3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [23]:
np.ones(10, dtype=np.int32)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int32)

In [24]:
np.full(shape=(4,4), fill_value='empty')

array([['empty', 'empty', 'empty', 'empty'],
       ['empty', 'empty', 'empty', 'empty'],
       ['empty', 'empty', 'empty', 'empty'],
       ['empty', 'empty', 'empty', 'empty']], dtype='<U5')

In [25]:
np.arange

<function numpy.arange>

In [26]:
np.arange(-2, 2, 0.5)

array([-2. , -1.5, -1. , -0.5,  0. ,  0.5,  1. ,  1.5])

In [27]:
np.random.randn(3, 3, 2)

array([[[ 0.10250965, -0.22403254],
        [-0.20627181, -1.53748231],
        [ 0.68284211,  0.71516513]],

       [[ 0.39131972, -2.79579011],
        [ 0.67001305,  0.50360638],
        [-1.12585818, -1.26843838]],

       [[ 0.39607037,  0.56869206],
        [-0.18539248, -0.83143386],
        [ 1.78888192, -0.48588617]]])

In [28]:
np.random.randint(low=1, high=7, size=10)

array([5, 5, 4, 1, 1, 4, 1, 3, 6, 3])

In [29]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [30]:
np.eye(5, 8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.]])

## Indexing arrays

Arrays in `NumPy` are 0-indexed. Indexing of 1-d arrays is very easy, just follow the pattern of *start*:*end*:*step*

In [31]:
a = np.arange(0, 10)

print(f"""{a}

First element: {a[0]}
First three elements: {a[0:3]}
Last element: {a[len(a)-1]} and {a[-1]}
Even elements: {a[::2]}
""")

[0 1 2 3 4 5 6 7 8 9]

First element: 0
First three elements: [0 1 2]
Last element: 9 and 9
Even elements: [0 2 4 6 8]



Indexing of n-dim arrays is a bit more tricky. Keep in mind that axis 0 refers to rows and axis 1 refers to columns. For high dimensional arrays try to build the following intuition:
- 1-d: a row of values
- 2-d: a matrix (rows and columns) of values
- 3-d: a row of arrays
- 4-d: a matrix of arrays
- and so on...

In [32]:
a = np.array([
    [1, 2, 3, 4],
    [10, 20, 30, 40],
    [100, 200, 300, 400],
])

print(f"""{a}

Element at second row, third column: {a[1,2]}
Entire first row: {a[0]}
Entire first row as 2-d array: {a[0, None]}
First and second rows, last column: {a[:2,-1]}
""")

[[  1   2   3   4]
 [ 10  20  30  40]
 [100 200 300 400]]

Element at second row, third column: 30
Entire first row: [1 2 3 4]
Entire first row as 2-d array: [[1 2 3 4]]
First and second rows, last column: [ 4 40]



The same goes with all n-dim arrays. For instance, let's extract first matrix, all rows, first column. You can also use indexing to assign multiple values to array cell at once.

In [33]:
a_3d

array([[[0, 0],
        [0, 1]],

       [[1, 0],
        [1, 1]]])

In [34]:
a_3d[0, :,0]

array([0, 0])

In [35]:
a_3d[1, :, 1] = -1

print(a_3d)

[[[ 0  0]
  [ 0  1]]

 [[ 1 -1]
  [ 1 -1]]]


## Basic operations on arrays

All array operations are vectorized, so they tend to be very quick. By default, `NumPy` performs element-wise array operations. If you want to correctly multiply arrays, use `@` operator as shown below.

In [36]:
a = np.arange(0, 12)
b = np.arange(12, 24)

a.shape = b.shape = 3, 4

In [37]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [38]:
b

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [39]:
a + b

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [40]:
b - a

array([[12, 12, 12, 12],
       [12, 12, 12, 12],
       [12, 12, 12, 12]])

In [41]:
a * 10

array([[  0,  10,  20,  30],
       [ 40,  50,  60,  70],
       [ 80,  90, 100, 110]])

In [42]:
a @ b.T

array([[ 86, 110, 134],
       [302, 390, 478],
       [518, 670, 822]])

## Homework

### Calculating sliding averages

Given an array of daily measurements, create a new array with averages computed over each pair of consecutive days. Compare the execution time of various solutions.

In the first solution you should use the for loop comprehension in order to create an array of pairs of measurements. Then, using the numpy average function calculate averages over the list of pairs.

In [43]:
measurements = np.arange(100)

In [44]:
[np.average([i, j]) for i, j in zip(measurements[:-1], measurements[1:])]

[0.5,
 1.5,
 2.5,
 3.5,
 4.5,
 5.5,
 6.5,
 7.5,
 8.5,
 9.5,
 10.5,
 11.5,
 12.5,
 13.5,
 14.5,
 15.5,
 16.5,
 17.5,
 18.5,
 19.5,
 20.5,
 21.5,
 22.5,
 23.5,
 24.5,
 25.5,
 26.5,
 27.5,
 28.5,
 29.5,
 30.5,
 31.5,
 32.5,
 33.5,
 34.5,
 35.5,
 36.5,
 37.5,
 38.5,
 39.5,
 40.5,
 41.5,
 42.5,
 43.5,
 44.5,
 45.5,
 46.5,
 47.5,
 48.5,
 49.5,
 50.5,
 51.5,
 52.5,
 53.5,
 54.5,
 55.5,
 56.5,
 57.5,
 58.5,
 59.5,
 60.5,
 61.5,
 62.5,
 63.5,
 64.5,
 65.5,
 66.5,
 67.5,
 68.5,
 69.5,
 70.5,
 71.5,
 72.5,
 73.5,
 74.5,
 75.5,
 76.5,
 77.5,
 78.5,
 79.5,
 80.5,
 81.5,
 82.5,
 83.5,
 84.5,
 85.5,
 86.5,
 87.5,
 88.5,
 89.5,
 90.5,
 91.5,
 92.5,
 93.5,
 94.5,
 95.5,
 96.5,
 97.5,
 98.5]

In [45]:
%%timeit
[np.average((i, j)) for i, j in zip(measurements[:-1], measurements[1:])]

472 µs ± 34 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In the second solution you are still supposed to create an array of pairs of measurements. This time use the numpy vstack to stack two duplicates of the measurements array. Cut the last day from the first duplicate, cut the first day from the second duplicate. Remember to check the validity of the solution, use transposition if necessary.

In [46]:
stack = np.vstack([measurements[:-1], measurements[1:]])

In [47]:
np.transpose(stack)

array([[ 0,  1],
       [ 1,  2],
       [ 2,  3],
       [ 3,  4],
       [ 4,  5],
       [ 5,  6],
       [ 6,  7],
       [ 7,  8],
       [ 8,  9],
       [ 9, 10],
       [10, 11],
       [11, 12],
       [12, 13],
       [13, 14],
       [14, 15],
       [15, 16],
       [16, 17],
       [17, 18],
       [18, 19],
       [19, 20],
       [20, 21],
       [21, 22],
       [22, 23],
       [23, 24],
       [24, 25],
       [25, 26],
       [26, 27],
       [27, 28],
       [28, 29],
       [29, 30],
       [30, 31],
       [31, 32],
       [32, 33],
       [33, 34],
       [34, 35],
       [35, 36],
       [36, 37],
       [37, 38],
       [38, 39],
       [39, 40],
       [40, 41],
       [41, 42],
       [42, 43],
       [43, 44],
       [44, 45],
       [45, 46],
       [46, 47],
       [47, 48],
       [48, 49],
       [49, 50],
       [50, 51],
       [51, 52],
       [52, 53],
       [53, 54],
       [54, 55],
       [55, 56],
       [56, 57],
       [57, 58],
       [58, 59

In [48]:
a = np.array([[1,2,3],[2,3,4]])
print(a)
print(a.T)

[[1 2 3]
 [2 3 4]]
[[1 2]
 [2 3]
 [3 4]]


In [49]:
%%timeit
[np.average((i, j)) for i, j in np.transpose(np.vstack([measurements[:-1], measurements[1:]]))]

488 µs ± 6.12 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In your third solution use the discrete convolution function. This time you calculate the averages with the convolution directly, you don't need to use average function here.

An example of discrete convolution:

given a filter $G=[g_1,g_2,g_3]$ and a vector (1st rank tensor) $V=[v_1,v_2,v_3,v_4,v_5,v_6]$ the convolution of the vector $V$ and a filter $G$ is calculated as follows:

$$V * G = [g_1\cdot v_1+g_2\cdot v_2+g_3\cdot v_3,$$
$$g_1\cdot v_2+g_2\cdot v_3+g_3\cdot v_4,$$
$$g_1\cdot v_3+g_2\cdot v_4+g_3\cdot v_5,$$
$$g_1\cdot v_4+g_2\cdot v_5+g_3\cdot v_6]$$

keep in mind that the filter can be of any size as long as each of its components (of the shape) is equal or lower than its equivalent in the tensor. However, the dimensionality of the filter has to be the same as the dimensionality of the tensor (the filter could be of a lower dimensionality, but then it should be interpreted as if it was of the same dimensionality as the tensor). Notice the similarity between sliding window and the convolution - in both cases you put a "window" or a "filter" on the data and move the window throughout the data. In the example above the window moves like this:

[**_1,2,3_**,4,5,6]

[1,**_2,3,4_**,5,6]

[1,2,**_3,4,5_**,6]

[1,2,3**_,4,5,6_**]


In [50]:
np.convolve(measurements, [0.5, 0.5])[1:-1]

array([ 0.5,  1.5,  2.5,  3.5,  4.5,  5.5,  6.5,  7.5,  8.5,  9.5, 10.5,
       11.5, 12.5, 13.5, 14.5, 15.5, 16.5, 17.5, 18.5, 19.5, 20.5, 21.5,
       22.5, 23.5, 24.5, 25.5, 26.5, 27.5, 28.5, 29.5, 30.5, 31.5, 32.5,
       33.5, 34.5, 35.5, 36.5, 37.5, 38.5, 39.5, 40.5, 41.5, 42.5, 43.5,
       44.5, 45.5, 46.5, 47.5, 48.5, 49.5, 50.5, 51.5, 52.5, 53.5, 54.5,
       55.5, 56.5, 57.5, 58.5, 59.5, 60.5, 61.5, 62.5, 63.5, 64.5, 65.5,
       66.5, 67.5, 68.5, 69.5, 70.5, 71.5, 72.5, 73.5, 74.5, 75.5, 76.5,
       77.5, 78.5, 79.5, 80.5, 81.5, 82.5, 83.5, 84.5, 85.5, 86.5, 87.5,
       88.5, 89.5, 90.5, 91.5, 92.5, 93.5, 94.5, 95.5, 96.5, 97.5, 98.5])

In [51]:
%%timeit
np.convolve(measurements, [0.5, 0.5])[1:-1]

2.12 µs ± 149 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In this solution use the numpy insert to add a 0 at the beginning of the measurements array (for padding purposes). Then calculate the cumulative sums of the measurements. Finally use the cumulative sum array in order to calculate the averages (it is a combination of picking elements in the correct order and a simple numerical operation). 

hint:

measurements = [1**,2,3,**4,5,6]

cumulative_sums = [0,**1**,3,**6**,10,15,21]

$$c_1 = x_0+x_1$$
$$c_3=x_0+x_1+x_2+x_3$$
$$c_3-c_1 = x_2+x_3$$

measurements = [1,2,**3,4**,5,6]

cumulative_sums = [0,1,**3**,6,**10**,15,21]

$$c_2 = x_0+x_1+x_2$$
$$c_2=x_0+x_1+x_2+x_3+x_4$$
$$c_3-c_1 = x_3+x_4$$



In [52]:
new_measurements = np.insert(measurements, [0], [0])

In [53]:
a = np.cumsum(new_measurements)
(a[2:] - a[:-2])/2

array([ 0.5,  1.5,  2.5,  3.5,  4.5,  5.5,  6.5,  7.5,  8.5,  9.5, 10.5,
       11.5, 12.5, 13.5, 14.5, 15.5, 16.5, 17.5, 18.5, 19.5, 20.5, 21.5,
       22.5, 23.5, 24.5, 25.5, 26.5, 27.5, 28.5, 29.5, 30.5, 31.5, 32.5,
       33.5, 34.5, 35.5, 36.5, 37.5, 38.5, 39.5, 40.5, 41.5, 42.5, 43.5,
       44.5, 45.5, 46.5, 47.5, 48.5, 49.5, 50.5, 51.5, 52.5, 53.5, 54.5,
       55.5, 56.5, 57.5, 58.5, 59.5, 60.5, 61.5, 62.5, 63.5, 64.5, 65.5,
       66.5, 67.5, 68.5, 69.5, 70.5, 71.5, 72.5, 73.5, 74.5, 75.5, 76.5,
       77.5, 78.5, 79.5, 80.5, 81.5, 82.5, 83.5, 84.5, 85.5, 86.5, 87.5,
       88.5, 89.5, 90.5, 91.5, 92.5, 93.5, 94.5, 95.5, 96.5, 97.5, 98.5])

In [54]:
%%timeit
a = np.cumsum(new_measurements)
(a[2:] - a[:-2])/2

3.94 µs ± 98 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


## Broadcasting

This is by far the most important concept in `NumPy`. Broadcasting is an automatic expansion of arrays so that they match with their operands.

Let's start with the simplest example.

In [55]:
a = np.arange(10)

a + 10

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

The same happens for 2-d arrays

In [56]:
a = np.array([
    [1, 2, 3, 4],
    [1, 4, 9, 16],
])

b = np.array([
    [0.1, 0.2, 0.3, 0.4]
])

In [57]:
a

array([[ 1,  2,  3,  4],
       [ 1,  4,  9, 16]])

In [58]:
b

array([[0.1, 0.2, 0.3, 0.4]])

In [59]:
a + b

array([[ 1.1,  2.2,  3.3,  4.4],
       [ 1.1,  4.2,  9.3, 16.4]])

In [60]:
a.shape, b.shape

((2, 4), (1, 4))

The simple rule for broadcasting is the following:

If we want to operate on two arrays `a` and `b`:
- moving backwards from the last dimension of each array, we check if their dimensions are the same or one equals 1
- if all of `a`'s dimensions are compatible with `b`'s dimensions, arrays `a` and `b` are compatible.

In [61]:
np.random.seed(1234)

a = np.random.randint(low = 1, high = 10, size = (3, 4))
a

array([[4, 7, 6, 5],
       [9, 2, 8, 7],
       [9, 1, 6, 1]])

In [62]:
b = np.random.randint(low = 1, high = 10, size = (3, 1))
b

array([[7],
       [3],
       [1]])

In [63]:
a + b

array([[11, 14, 13, 12],
       [12,  5, 11, 10],
       [10,  2,  7,  2]])

In [64]:
np.random.seed(1234)

a = np.random.randint(low = 1, high = 10, size = (3, 1, 4))
a

array([[[4, 7, 6, 5]],

       [[9, 2, 8, 7]],

       [[9, 1, 6, 1]]])

In [65]:
b = np.random.randint(low = 1, high = 10, size = (2, 1))
b

array([[7],
       [3]])

In [66]:
a + b

array([[[11, 14, 13, 12],
        [ 7, 10,  9,  8]],

       [[16,  9, 15, 14],
        [12,  5, 11, 10]],

       [[16,  8, 13,  8],
        [12,  4,  9,  4]]])

Sometimes it is useful to be able to manually modify the shape of the array. This can be done using the `np.newaxis` function (which is simply an alias for the `None` keyword)

In [67]:
a = np.array([1, 2, 3, 5, 7, 11, 13])

In [68]:
a

array([ 1,  2,  3,  5,  7, 11, 13])

In [69]:
a[:, np.newaxis]

array([[ 1],
       [ 2],
       [ 3],
       [ 5],
       [ 7],
       [11],
       [13]])

In [70]:
a[None, :]

array([[ 1,  2,  3,  5,  7, 11, 13]])

This can be very useful if one wants to build an array containing the results of a cross-join operation on two matrices. Suppose we are trying to create $c_{ij} = a_i - b_j$.

In [71]:
b = np.arange(7)
c = a[:, None] - b[None, :]
c

array([[ 1,  0, -1, -2, -3, -4, -5],
       [ 2,  1,  0, -1, -2, -3, -4],
       [ 3,  2,  1,  0, -1, -2, -3],
       [ 5,  4,  3,  2,  1,  0, -1],
       [ 7,  6,  5,  4,  3,  2,  1],
       [11, 10,  9,  8,  7,  6,  5],
       [13, 12, 11, 10,  9,  8,  7]])

## Homework

### Battleships

Given a 10x10 playing field with hidden battleships and a list of shooting targets, compute the number of hits. You are only allowed to use the following functions:

 - ndarray.take
 - ndarray.T
 - ndarray.shape



In [72]:
sea = np.random.randint(low=0, high=2, size=(10,10))


In [73]:
targets = np.array([
    [0,3],
    [1,7],
    [2,2],
    [3,5],
    [8,2]
])

In [74]:
hits = sea.take(targets[:, 0] * sea.shape[1] + targets[:, 1])
hits @ hits.T

1

## Boolean indexing

Anytime you have a boolean array, you can use it to mask entries in another array.

In [75]:
a = np.random.randint(0, 100, size=(5,5))
a

array([[90, 33, 21, 71, 68],
       [81, 52, 64, 85, 41],
       [ 1, 14,  3, 30, 12],
       [73, 19, 26, 96, 68],
       [64, 22, 56, 84,  8]])

In [76]:
mask = a > 80
mask

array([[ True, False, False, False, False],
       [ True, False, False,  True, False],
       [False, False, False, False, False],
       [False, False, False,  True, False],
       [False, False, False,  True, False]])

In [77]:
a[mask]

array([90, 81, 85, 96, 84])

Boolean masking may be applied not only to values, but to rows and columns as well. Just remember to use slicing:

*array*[*row_mask*,*col_mask*]

In [78]:
rows_2_and_4 = np.array([False, True, False, True, False])
cols_1_and_2 = np.array([True, True, False, False, False])

In [79]:
a[rows_2_and_4]

array([[81, 52, 64, 85, 41],
       [73, 19, 26, 96, 68]])

In [80]:
a[rows_2_and_4, cols_1_and_2]

array([81, 19])

In [81]:
names = np.array(["Dennis", "Dee", "Charlie", "Mac", "Frank"])
ages = np.array([43, 44, 43, 42, 74])
genders = np.array(['male', 'female', 'male', 'male', 'male'])

In [82]:
names[(genders == 'male') & (ages > 43)]

array(['Frank'], dtype='<U7')

In [83]:
names[~(genders == 'male') & (ages % 2 == 0)]

array(['Dee'], dtype='<U7')

## `Random` module

One of the most frequently used parts of the `NumPy` is the random number generation procedure. Below you can see examples of different samples:
- normal sample
- uniform sample
- choosing from a set with/without replacement

In [84]:
np.random.normal(loc=10.0, scale=1.0, size=10)

array([10.13096188, 10.2627855 , 11.02376449,  9.93740495,  8.81769971,
        9.65524926,  9.75450933,  8.97400477, 10.05442481,  9.59315142])

In [85]:
np.random.randint(low=10, high=20, size=(3,3))

array([[11, 19, 12],
       [17, 14, 13],
       [12, 15, 15]])

In [86]:
np.random.uniform(low=0, high=1, size=5)

array([0.04653158, 0.91735447, 0.15893009, 0.94338268, 0.76316153])

In [87]:
np.random.choice(
    a=[1,2,3,4,5,6],
    replace=True,
    size=5
)

array([2, 1, 4, 2, 2])

In [88]:
np.random.choice(
    a=['this','is','sampling','without','replacement'],
    replace=False,
    size=3
)

array(['this', 'sampling', 'replacement'], dtype='<U11')

Despite the fact that most people use the `random` module as above, this way is in fact deprecated, because it introduces a dependency on the random number generator used currently by `NumPy`. In theory, if `NumPy` changes the generator, all the code becomes non-reproducible.
A simple solution is to use the generic `Generator` class.

In [89]:
generator = np.random.default_rng(seed=123)

In [90]:
generator.integers(low=1, high=100, size=10)

array([ 2, 68, 59,  6, 90, 22, 26, 19, 34, 18])

In [91]:
generator.normal(loc=0, scale=1, size=10)

array([ 0.57710379, -0.63646365,  0.54195222, -0.31659545, -0.32238912,
        0.09716732, -1.52593041,  1.1921661 , -0.67108968,  1.00026942])

In [92]:
generator.choice(a=[1,2,3], replace=True, size=10)

array([1, 2, 2, 3, 3, 1, 3, 3, 1, 2])

## Homework

### Two reviewers

You are given two arrays representing ratings assigned to 100 movies by two reviewers. Identify movies such that the reviewers differ in their rating by at most 1.

In [93]:
movies = np.arange(100)
reviewer_a = np.random.choice(a=[1,2,3,4,5], size=100)
reviewer_b = np.random.choice(a=[1,2,3,4,5], size=100)

In [94]:
movies_with_similar_review = movies[abs(reviewer_a - reviewer_b) <= 1]
movies_with_similar_review

array([ 3,  4,  5,  7,  8, 10, 12, 13, 14, 19, 21, 22, 23, 25, 26, 27, 33,
       35, 36, 37, 39, 42, 43, 44, 51, 52, 53, 54, 55, 56, 59, 63, 64, 65,
       66, 68, 69, 74, 75, 76, 77, 79, 82, 83, 84, 85, 86, 88, 89, 91, 92,
       96, 98, 99])

## Using `where`

`np.where` is a very useful function which allows to quickly filter elements of an array based on the condition. Imagine you have two large arrays and you want to create a third array such that it contains, for each cell, the larger value from the two arrays. First, let's do it in a traditional way.

In [95]:
a = np.random.randint(1, 6, size=10**5)
b = np.random.randint(1, 6, size=10**5)

In [96]:
%%time
c = np.zeros(a.size)

for i in range(a.size):
    if a[i] > b[i]:
        c[i] = a[i]
    else:
        c[i] = b[i]


CPU times: user 47 ms, sys: 1.25 ms, total: 48.3 ms
Wall time: 47.2 ms


In [97]:
%%time
d = np.where(a > b, a, b)

CPU times: user 408 µs, sys: 240 µs, total: 648 µs
Wall time: 428 µs


In [98]:
np.array_equal(c,d)

True

## Homework

### First to finish the assignment

Given an array with students' assignments ordered by the increasing date of submission, you want to reward first 3 students who submitted their work and who got at least 75 points. Increase their scores by 5 points.

In [99]:
grades = np.random.randint(low=0, high=100, size=50)
grades

array([37, 95, 59, 74, 84,  6, 78, 84, 34, 78, 51, 85, 46, 51, 86, 44, 12,
       18, 77, 26, 75, 57, 22, 56, 65, 10, 15, 63, 64, 31,  0,  4, 78, 69,
       81, 76, 53, 34, 35,  2, 22, 32, 80, 52,  7, 51, 32, 92, 79, 51])

In [100]:
grades[np.where(grades >= 75)[0][:3]] += 5
grades

array([ 37, 100,  59,  74,  89,   6,  83,  84,  34,  78,  51,  85,  46,
        51,  86,  44,  12,  18,  77,  26,  75,  57,  22,  56,  65,  10,
        15,  63,  64,  31,   0,   4,  78,  69,  81,  76,  53,  34,  35,
         2,  22,  32,  80,  52,   7,  51,  32,  92,  79,  51])

## Math functions

`NumPy` contains several highly optimized implementations of math functions. Whenever possible, try to use them instead of your own implementations. Remember, that math functions are easily generalized to n-dim arrays.

In [101]:
a = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16],
], dtype=np.float64)

In [102]:
np.sum(a)

136.0

In [103]:
np.sum(a, axis=0)

array([28., 32., 36., 40.])

In [104]:
np.sum(a, axis=1)

array([10., 26., 42., 58.])

But beware of `nan`s, as they tend to destroy all math!

In [105]:
a[2,2] = np.nan

In [106]:
np.sum(a)

nan

In [107]:
np.isnan(a)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False,  True, False],
       [False, False, False, False]])

In [108]:
np.sum(a, where=~np.isnan(a))

125.0

In [109]:
np.nansum(a)

125.0

In [110]:
np.sum(np.nan_to_num(a))

125.0

Let's see what else we can do with `nan`s

In [111]:
a[0,1] = np.nan
a[1,3] = np.nan

In [112]:
np.isnan(a)

array([[False,  True, False, False],
       [False, False, False,  True],
       [False, False,  True, False],
       [False, False, False, False]])

In [113]:
np.any(np.isnan(a), axis=1)

array([ True,  True,  True, False])

In [114]:
mask = np.any(np.isnan(a), axis=1)
a[mask]

array([[ 1., nan,  3.,  4.],
       [ 5.,  6.,  7., nan],
       [ 9., 10., nan, 12.]])

## Concatenation & sorting

Concatenation means joining two arrays by rows or by columns. An array may be concatenated with itself or with another array. There are 4 functions that help with concatenation.

In [115]:
a = np.zeros(shape=(3,2))
b = np.ones(shape=(2,2))

In [116]:
np.concatenate([a, a, a, a], axis=0)

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [117]:
np.concatenate([a, b], axis=0)

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.]])

In [118]:
np.vstack([a,b])

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.]])

In [119]:
np.hstack([a.T,b])

array([[0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 1.]])

In [120]:
np.stack([a[:2,:2], b], axis=0)

array([[[0., 0.],
        [0., 0.]],

       [[1., 1.],
        [1., 1.]]])

Unfortunately, `NumPy` does not provide any easy way of reverse sort, and sorting is limited to two functions.

In [121]:
a = np.random.randint(1, 100, size=50)
a

array([55, 12, 93, 14, 63, 16,  8, 71, 66,  7, 43, 33, 85, 94, 74, 53, 23,
       82, 82, 77, 97, 47, 34, 30, 57, 11, 15, 16, 72, 68, 21, 97, 31, 23,
        4, 22, 99, 65,  5, 80, 47, 62, 58,  6, 19,  1, 75, 51,  2, 71])

In [122]:
a.sort()

In [123]:
a

array([ 1,  2,  4,  5,  6,  7,  8, 11, 12, 14, 15, 16, 16, 19, 21, 22, 23,
       23, 30, 31, 33, 34, 43, 47, 47, 51, 53, 55, 57, 58, 62, 63, 65, 66,
       68, 71, 71, 72, 74, 75, 77, 80, 82, 82, 85, 93, 94, 97, 97, 99])

In [124]:
np.sort(a)[::-1]

array([99, 97, 97, 94, 93, 85, 82, 82, 80, 77, 75, 74, 72, 71, 71, 68, 66,
       65, 63, 62, 58, 57, 55, 53, 51, 47, 47, 43, 34, 33, 31, 30, 23, 23,
       22, 21, 19, 16, 16, 15, 14, 12, 11,  8,  7,  6,  5,  4,  2,  1])

If you want to be able to sort values in the first column of an array according to the order in the second column of an array, you need to use `np.argsort`.

In [125]:
a = np.random.randint(1, 100, size=20)
a.shape = 5,4

a

array([[17, 62, 22, 34],
       [39,  1, 99, 91],
       [ 2, 99, 93, 68],
       [60, 11, 42, 63],
       [88, 63, 13, 98]])

In [126]:
np.sort(a, axis=1)

array([[17, 22, 34, 62],
       [ 1, 39, 91, 99],
       [ 2, 68, 93, 99],
       [11, 42, 60, 63],
       [13, 63, 88, 98]])

In [127]:
a

array([[17, 62, 22, 34],
       [39,  1, 99, 91],
       [ 2, 99, 93, 68],
       [60, 11, 42, 63],
       [88, 63, 13, 98]])

In [128]:
a[np.argsort(a[:,1])]

array([[39,  1, 99, 91],
       [60, 11, 42, 63],
       [17, 62, 22, 34],
       [88, 63, 13, 98],
       [ 2, 99, 93, 68]])